name: 'aws-eks-setup'

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    ## Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: MYEKS
      run: |
        
        terraform init
        echo "hello all"
        pwd
        ls -ltra
        echo "hi"
        

    # Checks that all Terraform configuration files adhere to a canonical format
    #- name: Terraform Format
      #working-directory: MYEKS
      #run: terraform fmt -check
    - name: test
      run: |
          cd MYEKS
          aws ec2 create-key-pair \
          --key-name ed-office \
          --region ap-south-1 \
          --query 'KeyMaterial' \
          --output text > ed-office.pem
          chmod 400 ed-office.pem

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::787089123165:role/github-actions-oidc-role
        aws-region: ap-south-1


    # Generates an execution plan for Terraform
    - name: Terraform Plan
      working-directory: MYEKS
      run: terraform plan -input=false


      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      working-directory: MYEKS
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        terraform import aws_iam_role.master ed-eks-master
        terraform import aws_iam_role.worker ed-eks-worker
        terraform apply -auto-approve -input=false

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false

